r"""
windbg_script.py — Generate WinDbg script for stepping through obfuscated code.

Outputs a .ws (WinDbg script) file that can be loaded via:
    $$>a<C:\path\to\script.ws

Or a .cmds one-liner file that can be run via:
    WinDbg -c "$<C:\path\to\one-liners.txt" ...

The script uses bp (set breakpoint), g (go), r (dump registers), and
.printf to log each call.

Usage (PowerShell on Flare-VM):
    PS> python C:\tools\flarevm-deploy\dynamic\windbg_script.py --target C:\samples\foo.exe --apis "VirtualAlloc,WriteProcessMemory" --out C:\samples\foo.windbg.ws

Then in WinDbg:
    File > Open Executable: foo.exe
    .load wow64exts   (if 32-bit on 64-bit)
    $$>a<C:\samples\foo.windbg.ws

Notes:
    - WinDbg script syntax differs from x64dbg; see https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/dot-script
    - For 32-bit targets, use the 32-bit WinDbg (dbgeng.dll x86)
"""
import argparse
from pathlib import Path


def main():
    ap = argparse.ArgumentParser(description="Generate WinDbg script")
    ap.add_argument("--target", help="path to PE binary (for context only)")
    ap.add_argument("--apis", required=True,
                    help="comma-separated API names to break on")
    ap.add_argument("--entry-bp", action="store_true",
                    help="also break at module entry point")
    ap.add_argument("--max-breaks", type=int, default=200)
    ap.add_argument("--out", required=True, help="output .ws script file")
    args = ap.parse_args()

    api_list = [a.strip() for a in args.apis.split(",") if a.strip()]
    if not api_list:
        print("FATAL: --apis is empty")
        return 1

    lines = [
        '$$ WinDbg script generated by windbg_script.py',
        f'$$ Target: {args.target or "(set in WinDbg)"}',
        f'$$ APIs: {", ".join(api_list)}',
        f'$$ Max breaks: {args.max_breaks}',
        '',
        '$$ --- Set breakpoints at APIs (resolve via `x <module>!<api>`) ---',
    ]
    # We use a single approach: bp on the API name; WinDbg will resolve across loaded modules
    for api in api_list:
        lines.append(f'bp {api}')
    if args.entry_bp:
        lines.append('bp $exentry')

    lines += [
        '',
        '$$ --- Run, log, repeat ---',
        '.printf "\\n--- WinDbg trace starting ---\\n";',
        f'.printf "Max breaks: {args.max_breaks}\\n";',
        'r;',
        'g',
        '',
        '.printf "--- WinDbg trace ended ---\\n";',
        'q',
    ]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
