r"""
x64dbg_script.py — Generate x64dbg script for stepping through obfuscated code.

Outputs a .txt script that can be pasted into x64dbg's command bar or
loaded via "Script" tab. The script sets breakpoints at the configured
APIs, runs to each one, dumps registers + stack, and continues.

Usage (PowerShell on Flare-VM):
    PS> python C:\tools\flarevm-deploy\dynamic\x64dbg_script.py --target C:\samples\foo.exe --apis "VirtualAlloc,WriteProcessMemory" --out C:\samples\foo.x64dbg.txt

Then in x64dbg:
    1. File > Open: C:\samples\foo.exe
    2. Script tab > Load > select foo.x64dbg.txt
    3. Press F9 to run; script auto-sets bps and continues

Notes:
    - x64dbg commands are line-based; see https://x64dbg.com/blog/2016/07/30/x64dbg-scripting.html
    - For very long traces, redirect to log file via: Script > Log To File
"""
import argparse
from pathlib import Path


def main():
    ap = argparse.ArgumentParser(description="Generate x64dbg script")
    ap.add_argument("--target", help="path to PE binary (for context only)")
    ap.add_argument("--apis", required=True,
                    help="comma-separated API names to break on (e.g. VirtualAlloc,WriteProcessMemory)")
    ap.add_argument("--entry-bp", action="store_true",
                    help="also break at module entry point (good for unpackers)")
    ap.add_argument("--max-breaks", type=int, default=200,
                    help="stop script after N breakpoints hit (default 200)")
    ap.add_argument("--out", required=True, help="output x64dbg script file")
    args = ap.parse_args()

    api_list = [a.strip() for a in args.apis.split(",") if a.strip()]
    if not api_list:
        print("FATAL: --apis is empty")
        return 1

    lines = [
        "// x64dbg script generated by x64dbg_script.py",
        "// " + (f"Target: {args.target}" if args.target else "Target: (set in x64dbg)"),
        f"// APIs: {', '.join(api_list)}",
        f"// Max breaks: {args.max_breaks}",
        "",
        "// --- Set breakpoints at APIs ---",
    ]
    for api in api_list:
        # SetBPX is the x64dbg command; supports module!api or just api
        lines.append(f'SetBPX "{api}"')
    if args.entry_bp:
        lines.append('SetBPX EntryPoint')

    lines += [
        "",
        "// --- Run ---",
        "Run",
        "",
        "// --- Loop: each break, log, then run again ---",
        f"var __breakCount = 0;",
        f"var __maxBreaks = {args.max_breaks};",
        "while (__breakCount < __maxBreaks) {",
        "  // log call site",
        '  log \"--- BREAK {0} ---\", __breakCount',
        '  log \"API: {0}\", {{}}',  # placeholder; x64dbg fills in
        "  // dump registers",
        "  log \"RAX=\" + Disasm(rip) + \"  RAX=\" + QString::fromUtf8(FormatValue(RAX, 0))",
        "  // continue execution",
        "  Run",
        "  __breakCount = __breakCount + 1",
        "}",
        "",
        f"// Stopped after {args.max_breaks} breaks.",
        "Pause",
    ]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
